services:
  - type: web
    name: notion-telegram-tasks-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_DATABASE_ID
        value: 0fffed8ebc6348b699f24122c59fffc9
      - key: ADMIN_IDS
        value: 486058343,1530089636
      - key: POLL_INTERVAL_SECONDS
        value: "60"
